version: '3'

services:
  web:
    environment:
      TZ: Asia/Tokyo
    build: .
    volumes:
      - .:/usr/src/app
      - ./static/:/usr/src/app/static
    tty: true
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: gunicorn app.wsgi -b 0.0.0.0:8000

  nginx:
    image: nginx
    ports:
      - 80:80
    expose:
      - 80
    volumes:
      - ./nginx/:/etc/nginx/
      - ./static/:/etc/nginx/static/
    depends_on:
      - web

  postgres:
    restart: always
    image: postgres:12.2
    stdin_open: true
    tty: true
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $DB_USER_NAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME

