version: '3'

services:
  web:
    environment:
      TZ: Asia/Tokyo
    build: .
    volumes:
      - .:/usr/src/app
    tty: true
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: gunicorn config.wsgi -b 0.0.0.0:8000

  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/
      - ./static:/usr/src/app/static
      - ./templates:/usr/src/app/templates
      - ./media:/usr/src/app/media
    depends_on:
      - web

  postgres:
    restart: always
    image: postgres:12.2
    stdin_open: true
    tty: true
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $DB_USER_NAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME

