# Generated by Django 3.0.6 on 2020-12-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='introduction',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='自己紹介文'),
        ),
    ]
